### PR TITLE
MANIFEST.in: Add LICENSE and docs to sdist

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/scalative/haas/issues/184

### CODE REVIEW

**Comment by jayvdb** [comment]
fwiw, I also have some failures in https://build.opensuse.org/package/show/home:jayvdb:py-new/python-haas , likely due to stevedore version mismatch .. ?

**Comment by itziakos** [comment]
@jayvdb sorry for the late reply. We have fixed the ci builds. Can you rebase your PR on top of the current branch so that the new changes are picked up?

**Comment by jayvdb** [comment]
@itziakos done ;-)

**Comment by itziakos** [comment]
Hi, @sjagoe when you have time please merge the PR, I do not have the merge rights.

**Pull request merged**
