### PR TITLE
Drive-by flake8 fixes

### PR DESCRIPTION
**Pull request by jvkersch**
Just a couple of nitpicks to let flake8 run cleanly on the haas codebase. I didn't address `E402 module level import not at top of file` since that would have materially altered the code (and can be whitelisted).

@sjagoe Would you be interested in running flake8 or another linter as part of CI?

### CODE REVIEW

**Comment by sjagoe** [comment]
@jvkersch Yes, I think we do want it in CI.

**Comment by jvkersch** [comment]
Thanks @sjagoe. If you don't mind, I'll keep this open until #175 is merged and then I'll add the CI.

**Comment by sjagoe** [comment]
I've set up flake8 CI in #179, building on the work done in #175.

**Comment by sjagoe** [comment]
Given that this is only two commits, I've cherry-picked them into #179 to allow CI to run without allowed-failures.

**Comment by jvkersch** [comment]
Thanks @sjagoe !

**Pull request closed without merging**
